export default [
    {
        src: "assets-playlists/src/something-stupid.mp3",
        name: "Something Stupid",
        artist: "Frank Sinatra & Nancy Sinatra",
        cover: "https://i.scdn.co/image/ab67616d0000b2733e2331ff09f59ea3c87fe5d6",
        lyrics: "I know I stand in line\nUntil you think you have the time\nTo spend an evening with me\nAnd if we go some place to dance\nI know that there's a chance\nYou won't be leaving with me\nThen afterwards we drop into a quiet little place\nAnd have a drink or two\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\nI can see it in your eyes\nThat you despise the same old lies\nYou heard the night before\nAnd though it's just a line to you\nFor me it's true\nAnd never seemed so right before\nI practice every day \nTo find some clever lines to say\nTo make the meaning come true\nBut then I think I'll wait\nUntil the evening gets late\nAnd I'm alone with you\nThe time is right, your perfume fills my head\nThe stars get red, and, oh, the night's so blue\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\nThe time is right, your perfume fills my head\nThe stars get red, and, oh, the night's so blue\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\n'I love you'\n'I love you\n'I love you'\n'I love you'",
    },
    {
        src: "assets-playlists/src/zombie.mp3",
        name: "Zombie",
        artist: "The Cranberries",
        cover: "https://i.scdn.co/image/ab67616d0000b273e2213d84fabb15100c425198",
        lyrics: "Another head hangs lowly\nChild is slowly taken\nAnd the violence caused such silence\nWho are we mistaken?\nBut you see, it's not me, it's not my family\nIn your head, in your head, they are fightin'\nWith their tanks and their bombs\nAnd their bombs and their guns\nIn your head, in your head, they are cryin'\nIn your head, in your head\nZombie, zombie, zombie-ie-ie\nWhat's in your head, in your head?\nZombie, zombie, zombie-ie-ie-ie, oh\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nAnother mother's breakin'\nHeart is taking over\nWhen the violence causes silence\nWe must be mistaken\nIt's the same old theme, since 1916\nIn your head, in your head, they're still fightin'\nWith their tanks and their bombs\nAnd their bombs and their gun\nIn your head, in your head, they are dyin'\nIn your head, in your head\nZombie, zombie, zombie-ie-ie\nWhat's in your head, in your head?\nZombie, zombie, zombie-ie-ie-ie\nOh-oh-oh-oh-oh-oh-oh\nEh-eh, oh, ya-ya\n",
    },
    {
        src: "assets-playlists/src/clint-eastwood.mp3",
        name: "Clint Eastwood",
        artist: "Gorillaz",
        cover: "https://i.scdn.co/image/ab67616d0000b273c73a7bb15f43bae86215934b",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/apocalypse.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/505.mp3",
        name: "505",
        artist: "Arctic Monkeys",
        cover: "https://i.scdn.co/image/ab67616d0000b2730c8ac83035e9588e8ad34b90",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/there-is-a-light-that-never-goes-out.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/let-it-happen.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/thats-life.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/é-preciso-saber-viver.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/otherside.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/my-way.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/freaking-out-the-neighborhood.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/dont-look-back-in-anger.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/the-less-i-know-the-better.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/baby-blue.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/heart-attack.mp3",
        name: "Heart Attack (츄)",
        artist: "LOONA",
        cover: "https://i.scdn.co/image/ab67616d0000b273b6ab7be3b4eeb27e1af65cdb",
        lyrics: "Are you ready? (Ah)\nYou attack my heart\nYou attack my heart (Ah)\nYou attack my heart\nYou attack my heart (Damn)\n우리 처음 봤던 날 조용했던 내 맘 속\n새로운 세상이 열린 듯\n유난히 빨라지던 move\n나 혼자 알고 있었던 감춰진 내 비밀도\n너에게 딱 내 전부다\n말하고 싶어지던 mood\n나 한 걸음 먼저 널 향해 먼저\n다가간 모습에\n숨어있던 날 만나게 돼 (Oh)\n점점 더 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득히\n아찔한 기분이\n이런 건가 봐, darling\n점점 더 난 네게 빠져가\nYou attack my heart\nYou attack my heart\nYou attack my heart (Ah)\nYou attack my heart\nYou attack my heart (Damn)\n이런 게 fall in love 하얀 내 맘에\n너를 담았더니 빨간색이 돼\n멈출 수 없이 자꾸 떠올라\n유난히 더 많이 생각하게 돼\n내 모든 기준들이 너로 정해져 버리듯\n지구를 맴맴 도는 저기 달처럼\n우린 ooh-ooh, 만나게 될 거야\nOn the ooh-ooh-ooh, on the love trail\n널 보면 반짝 내 맘에 반짝\n불꽃이 튀는 듯\n숨어있던 맘을 알게 돼 (Oh)\n점점 더 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득히\n아찔한 기분이\n이런 건가 봐, darling\n점점 더 난 네게 빠져가\nYou attack my heart\n시간의 흐름도 모를 만큼\nAnywhere, anywhere, 널 생각해\nAnytime, anyplace, 너로 가득\n끝없이 퍼져\n조금 더 가까이 다가와줘\n우리 둘 함께 마주한다면\n상상조차 달콤하게만\n느껴져\n널 향해 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득해\n점점 더 선명해진 맘\n전부 다 줄게 take my heart\n분명 우리는 destiny (Destiny)\n빛이나 이 밤 가득히\n달콤한 중독이\n이런 건가 봐, darling\n더 깊이 너에게 빠져가 (Ooh-ooh, ooh-ooh)\n점점 더 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득히 (Take my, take my heart)\n아찔한 기분이\n이런 건가 봐, darling\n점점 더 난 네게 빠져가\nYou attack my heart",
    },
    {
        src: "assets-playlists/src/pelados-em-santos.mp3",
        name: "Pelados Em Santos",
        artist: "Mamonas Assassinas",
        cover: "https://i.scdn.co/image/ab67616d0000b2733982e253126c959ab9677bcb",
        lyrics: "Mina, seus cabelo é da hora, seu corpo violão\nMeu docinho de coco, tá me deixando louco\nMinha Brasília amarela tá de portas abertas\nPra mode a gente se amar pelados em Santos\nPois você, minha pitchula, me deixou legalzão\nNão me sinto sozinho, você é meu chuchuzinho\nMusic is very good\n(Oxente ai, ai, ai)\nMas comigo, ela não quer se casar\n(Oxente ai, ai, ai)\nNa Brasília amarela com roda Gaúcha, ela não quer entrar\n(Oxente ai, ai, ai)\nÉ, feijão com jabá, desgraçada, não quer compartilhar\nMas ela é linda\nMuito mais do que linda\nVery, very beautiful\nVocê me deixa doidão\nOh, yes, oh, no's\nMeu docinho de coco\nMusic is very porreta\n(Oxente, Paraguai)\nPros Paraguai, ela não quis viajar\n(Oxente, Paraguai)\nComprei um Reebok e uma calça Fiorucci, ela não quer usar\n(Oxente, Paraguai)\nEu não sei o que faço, pra essa mulher eu conquistar\nPorque ela é linda\nMuito mais do que linda\nVery, very beautiful\nVocê me deixa doidão\nOh, yes, oh, no's\nMeu chuchuzinho\nOh, yes, no, no, no, no\nEu te I love you\nPeraí, que tem mais um pouquinho de 'u'\nUuuuu\nTchê",
    },
    {
        src: "assets-playlists/src/sabor-cowboy.mp3",
        name: "Sabor Cowboy",
        artist: "Marco Brasil Filho, João Nelore & Texano, Dj Kevin",
        cover: "https://i.scdn.co/image/ab67616d0000b273eb429813b201cc73db4fd9b4",
        lyrics: "Sabor\nJoão Nelore e Texano\nDJ Kelvin e o Marco Brasil Filho!\nCuidado muierada' tem que ver certinho\nQuem cês sai pegando pra não se dar mal\nTá cheio de peão farso' por aí\nSe passando por peão original\nMas nunca pisou na roça\nNão sabe o que é um farpado\nNão conhece uma moda\nAs bota nunca viu barro\nMas nunca pisou na roça\nNão sabe o que é um farpado\nEsses cara pode ser tudo\nMas nunca vai ser do agro (DJ Kevin!)\nTem caminhonete, cartão black\nE se veste igual nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE tenta copiar nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE se veste igual nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE tenta copiar nós, mas não é cowboy\nÓ, ó, é sabor, sabor cowboy\nTentar, eles até que tenta\nMas não consegue, não!\nSabor\nJoão Nelore e Texano\nDJ Kevin, MBF\nMarco Brasil Filho\nMas nunca pisou na roça\nNão sabe o que é um farpado\nNão conhece uma moda\nAs bota nunca viu barro\nMas nunca pisou na roça\nNão sabe o que é um farpado\nEsses cara pode ser tudo\nMas nunca vai ser do agro (DJ Kevin!)\nTem caminhonete, cartão black\nE se veste igual nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE tenta copiar nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE se veste igual nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE tenta copiar nós, mas não é cowboy\nÉ sabor cowboy\nTem caminhonete, cartão black\nE se veste igual nós, mas não é cowboy\nÉ sabor (sabor)\nComo não, comboca'?\nMeu Deus do céu!\n(Sabe qual o segredo do meu drink?)\n(É sabor energético, um segredinho!)",
    },
    {
        src: "assets-playlists/src/triple-baka.mp3",
        name: "Triple Baka",
        artist: "ラマーズP (Lamaze-P), Hatsune Miku, Akita Neru, Kasane Teto",
        cover: "https://i.scdn.co/image/ab67616d0000b2734cbf7f307793e3ccac71ce9b",
        lyrics: "あなたの心をバッキュンキュン\n気がつけばモニターの前で おはよっ\nしらないあいだに\nねむけ あらわれた\n(あーうーあーうー)\nいそがしいのに あまえながら よせる\n言葉に誘われ\n「君は実にバカだなあ」\n「本気で釣られたあ」\nかんぺきにまにあわない\nどうしようもないそのとき\nひらめいたなにかにより\nすぐにあきらめた\nバカ、バカ、バカ\n何がここまであなたをうごかすの？ (うーごーかーすーのー)\n未知なる世界へ 飛び立つ\n希望乗せ\nバカ、バカ、バカ\n他にやることまだまだあるんじゃない？(たーくーさーんーのー)\nないて わらって おこること\n任せてね\nわたしの色にしてあげる\nクリエイティブな心は折れないさ\nそうは言うけれど\nすでにくずれてた\n(「オイ、それはだめだろ」)\nなあに またもちなおせば ほら やる気\nたくさんあふれる\nすなどけいのように\nてきとーにつくりあげる\nだけどなにかものたりず\nネタをさがしてみたけど\nちからつきてきた\nバカ、バカ、バカ\nまちぼうけなのにてぬきとかひどいよ (ひーどーすーぎーDAー)\n本気だせば 幸せでしょ？\nあなたなら\nバカ、バカ、バカ\nやるべきことは すべてわすれちゃえ (すてちゃえyo)\nうたう おどる えがく ことば\nくりだす\nわたしのために (Okay)\n( ＾ω＾)おっ　おっ　おっ　おっ(＾ω＾ )\n​( ＾ω＾)​おっおっ　おーっ　おっ(＾ω＾ )\n​( ＾ω＾)​おっおっ　おーっ　おっ(＾ω＾ )\n( ＾ω＾)​ テトペッテンソ～ン (＾ω＾ )\nバカ、バカ、バカ\n何がここまであなたをうごかすの？ (うーごーかーすーのー)\n未知なる世界へ 飛び立つ\n希望乗せ\nバカ、バカ、バカ\n他にやることまだまだあるんじゃない？ (たーくーさーんーのー)\nないて わらって おこること\n任せてね\nバカ、バカ、バカ\nまちぼうけなのに てぬきとかひどいよ (ひーどーすーぎーDAー)\n本気だせば 幸せでしょ？\nあなたなら\nバカ、バカ、バカ\nやるべきことは すべてわすれちゃえ (すてちゃえyo)\nうたう おどる えがく ことば\nおくりだす\nあなたの色にしてあげりゅううううううう",
    },
    {
        src: "assets-playlists/src/smile.mp3",
        name: "Smile",
        artist: "Lily Allen",
        cover: "https://i.scdn.co/image/ab67616d0000b273903b3846b9843677ca51bad9",
        lyrics: "When you first left me\nI was wantin' more\nBut you were fucking that girl next door\nWhat'd you do that for? (What'd you do that for?)\nWhen you first left me\nI didn't know what to say\nI never been on my own that way\nJust sat by myself all day\nI was so lost back then\nBut with a little help from my friends\nI found a light in the tunnel at the end\nNow you're calling me up on the phone\nSo you can have a little whine and a moan\nAnd it's only because you're feelin' alone\nAt first, when I see you cry\nYeah, it makes me smile\nYeah, it makes me smile\nAt worst, I feel bad for a while\nBut then I just smile\nI go ahead and smile \nWhenever you see me\nYou say that you want me back (Want me back)\nAnd I tell you it don't mean jack (It don't mean jack)\nNo, it don't mean jack (No, it don't mean jack)\nI couldn't stop laughin'\nNo, I just couldn't help myself (Help myself)\nSee, you messed up my mental health\nI was quite unwell\nI was so lost back then\nBut with a little help from my friends\nI found a light in the tunnel at the end\nNow you're calling me up on the phone\nSo you can have a little whine and a moan\nAnd it's only because you're feelin' alone\nAt first, when I see you cry\nYeah, it makes me smile\nYeah, it makes me smile\nAt worst, I feel bad for a while\nBut then I just smile\nI go ahead and smile\nLa-la-la, la-la-la, la-la-la, la-la-la\nLa-la-la, la-la-la, la-la-la, la-la-la\nLa-la-la, la-la-la, la-la-la, la-la-la, la-la-la\nAt first, when I see you cry (When I see you cry)\nYeah, it makes me smile (It makes me smile)\nYeah, it makes me smile (Yeah, it makes me smile)\nAt worst, I feel bad for a while (I feel bad for a while)\nBut then I just smile (But then I just smile)\nI go ahead and smile (I go ahead and smile)\n(La-la-la, la-la-la, la-la-la, la-la-la)\n(La-la-la, la-la-la, la-la-la, la-la-la)\n(La-la-la, la-la-la, la-la-la, la-la-la, la-la-la)\nAt first, when I see you cry (When I see you cry)\nYeah, it makes me smile (It makes me smile)\nYeah, it makes me smile (It makes me smile)\nAt worst, I feel bad for a while (I feel bad for a while)\nBut then I just smile (But then I just smile)\nI go ahead and smile (I go ahead and smile)",
    },
    {
        src: "assets-playlists/src/diga-sim-pra-mim.mp3",
        name: "Diga Sim pra Mim",
        artist: "Desejo De Menina",
        cover: "https://i.scdn.co/image/ab67616d0000b2730608a3c6880ab70a40eb7827",
        lyrics: "Desejo de Menina\nEu pensei em comprar algumas flores\nSó pra chamar mais atenção\nEu sei, já não há mais razão pra solidão\nMeu bem (meu bem), eu tô pedindo a sua mão\nEu pensei em escrever alguns poemas\nSó pra tocar seu coração\nEu sei, uma pitada de romance é bom\nMeu bem (meu bem), eu tô pedindo a sua mão\nEntão case-se comigo numa noite de luar\nOu na manhã de um domingo à beira-mar\nDiga sim pra mim\nCase-se comigo na igreja e no papel\nVestido branco com buquê e lua de mel\nDiga sim pra mim\nAh, sim pra mim\nPrometo sempre ser o seu abrigo\nNa dor o sofrimento é dividido\nLhe juro ser fiel ao nosso encontro\nNa alegria, felicidade vem em dobro\nEu comprei uma casinha tão modesta\nEu sei, você não liga pra essas coisas\nTe darei toda riquesa de uma vida\nÔ meu amor\nDesejo de Menina\nEntão case-se comigo numa noite de luar\nOu na manhã de um domingo à beira-mar\nDiga sim pra mim\nCase-se comigo na igreja e no papel\nVestido branco com buquê e lua de mel\nDiga sim pra mim\nEntão case-se comigo numa noite de luar\nOu na manhã de um domingo à beira-mar\nDiga sim pra mim\nCase-se comigo na igreja e no papel\nVestido branco com buquê e lua de mel\nDiga sim pra mim\nAh, sim pra mim, yeah",
    },
    {
        src: "assets-playlists/src/cradles.mp3",
        name: "Cradles",
        artist: "Sub Urban",
        cover: "https://i.scdn.co/image/ab67616d0000b273e57adcac43f4e49de7cdc65e",
        lyrics: "I live inside my own world of make-believe\nKids screaming in their cradles, profanities\nI see the world through eyes covered in ink and bleach\nCross out the ones who heard my cries and watched me weep\nI love everything\nFire's spreading all around my room\nMy world’s so bright\nIt's hard to breathe but that's alright\nHush\nShh\nTape my eyes open to force reality (Oh no, no)\nWhy can’t you just let me eat my weight in glee?\nI live inside my own world of make-believe\nKids screaming in their cradles, profanities\nSome days I feel skinnier than all the other days\nSometimes I can't tell if my body belongs to me\nI love everything\nFire's spreading all around my room\nMy world's so bright\nIt's hard to breathe but that's alright\nHush\nShh\nI wanna taste your content\nHold your breath and feel the tension\nDevils hide behind redemption\nHonesty is a one-way gate to hell\nI wanna taste consumption\nBreathe faster to waste oxygen\nHear the children sing aloud\nIt's music 'til the wick burns out\nHush\nJust wanna be care free lately, yeah\nJust kicking up daisies\nGot one too many quarters in my pockets\nCount ’em like the four-leaf clovers in my locket\nUntied laces, yeah\nJust tripping on daydreams\nGot dirty little lullabies playing on repeat\nMight as well just rot around the nursery and count sheep",
    },
    {
        src: "assets-playlists/src/chic-n-stu.mp3",
        name: "Chic 'N' Stu",
        artist: "System Of A Down",
        cover: "https://i.scdn.co/image/ab67616d0000b2737cf4c0d42c5b62c9deebdcd8",
        lyrics: "Ballgame's in the refrigerator\nDoor is closed\nLights are out\nButter's gettin' hard!\nWhat a splendid pie, pizza-pizza pie\nEvery minute and every second, buy, buy, buy, buy, buy\nWhat a splendid pie, pizza-pizza pie\nEvery minute and every second, buy, buy, buy, buy, buy\nPepperoni and green peppers, mushrooms, olive, chives\nPepperoni and green peppers, mushrooms, olive, chives\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nTherapy, therapy, advertising causes\nWhat a splendid pie, pizza-pizza pie\nEvery minute and every second, buy, buy, buy, buy, buy, buy\nWhat a splendid pie, pizza-pizza pie\nEvery minute and every second, buy, buy, buy, buy, buy\nPepperoni and green peppers, mushrooms, olive, chives\nPepperoni and green peppers, mushrooms, olive, chives\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nTherapy, therapy, advertising causes\nTherapy, therapy, advertising causes\nTherapy, therapy, advertising causes\nWell, advertising's got you on the run\nNeed therapy, therapy advertising causes\nWell, advertising's got you on the run\nNeed therapy, therapy advertising causes\nWell, advertising's got you on the run\nAdvertising's got you on the run\nAdvertising's got you on the run\nAdvertising's got you on the run\nAdvertising's got you on the run\nAdvertising's got you on the run\nAdvertising's got you on the run!\nWhat a splendid pie, pizza-pizza pie\nEvery minute and every second, buy, buy, buy, buy, buy, buy\nWhat a splendid pie, pizza-pizza pie\nEvery minute and every second, buy, buy, buy, buy, buy\nPepperoni and green peppers, mushrooms, olive, chives\nPepperoni and green peppers, mushrooms, olive, chives\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nTherapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes\nNeed therapy, therapy, advertising causes need",
    },
    {
        src: "assets-playlists/src/yummy.mp3",
        name: "Yummy",
        artist: "Ayesha Erotica",
        cover: "https://i.scdn.co/image/ab67616d0000b27370cdf4fc0b6b2dc937e2290e",
        lyrics: "Tum— edi-edi-edi-ed—\nDu-du-du-du— tummy\nFeeling edi-edi-edi-ed—\nDu-du-du-du, —eeling\nFeeling yummy, yummy\nYummy, yummy, my-my-my-my\nMy tummy feeling edi-edi-edi-ed—\nDu-du-du-du—\nTummy feeling edi-edi-edi-ed—\nDu-du-du-du— tummy\nFeeling edi-edi-edi-ed—\nDu-du-du-du, —eeling\nFeeling yummy, yummy\nYummy, yummy, my-my-my-my\nMy tummy feeling edi-edi-edi-ed—\nDu-du-du-du—\nTummy full of edible gummies, I'm feeling yummy\nJuicy tracksuit whenever I'm feeling bummy\nBig heels, got the Pleasers, I'm pleasing 'em, something funny\nBaby Phat jizz rag whenever he's feeling cummy\nYeah, you bucktooth Beckies can't rhyme for shit\nHeard your record and your lines sound just like his\nSee, the difference me and you, bitch, my shit hits\nYou're a size too big, bitch, and my shit fits\nI'm the First Lady of Juicy Couture\nGot a little cash now, so the skirt is Dior\nAnd my lips look just like Amanda Lepore's\nNow the kids out screaming, 'You were better before'\nBefore what? Bitch, still snorting away\nStill sipping Red Bull, 'bout a gallon a day\nStill rocking chinchilla knowing I didn't pay\nDrop-top, pink coupe, bitch, get out of my way, ayy\nTummy full of edible gummies, I'm feeling yummy\nTum-tum-tummy full of edible gummies, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nTum-tum-tummy full of edible gummies\nI'm feeling yummy, yummy\nTummy full of edible gummies, I'm feeling yummY\nTum-tum-tummy full of edible gummies, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nTum-tum-tummy full of edible gummies, I'm feeling yummy\nYeah, big purse with the rhinestone buckle\nKeep a pink stun gun just in case I'm in trouble\nDouble double, yeah, they asking for the fries on the side\nBut I never take 'em home unless it's eyes on the ride\nRun with cokeheads, yeah, they rock my threads\nLet 'em spend the night in my hot pink bed\nMaybe send 'em home with a lot more bread\nI'm just tryna keep all the porn stars fed\nYeah, he love me, but he fucks me like he hates my guts\nHe hit the spot to make me squirt and let me paint his nuts\nHe paid me right then, right there when he bust\nI'm a fake bitch, so I'm paying him dust\nI do it for the girls and the gays, that's it\nThe queens and the queers, yeah, they loving my shit\nYeah, shout the fuck out to the girls with the big-ass lips\nAnd shout the fuck out to the girls with the big-ass dicks, stay up\nTummy full of edible gummies, I'm feeling yummy\nTum-tum-tummy full of edible gummies, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nTum-tum-tummy full of edible gummies\nI'm feeling yummy, yummy\nTummy full of edible gummies, I'm feeling yummy\nTum-tum-tummy full of edible gummies, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nI'm feeling, I'm feeling yummy\nTum-tum-tummy full of edible gummies, I'm feeling yummy",
    },
    {
        src: "assets-playlists/src/tiki-tiki.mp3",
        name: "TIKI TIKI (Slowed)",
        artist: "QMIIR, SLIMA CHICA",
        cover: "https://i.scdn.co/image/ab67616d0000b27301913aba303b2a409c0cd157",
        lyrics: "Tiki-tiki-tiki\nMa-te-te-ki-ta-ka-ta\nTiki-tiki-tiki, tiki-ti\nTiki-tiki-ti\nTiki-tiki-ti, ti-ti\nTe-te-ki-ta-ka\nTi\nTi\nTi\nTiki\nMa-te-te-ki-ta-ka-ta\nTiki-tiki-tiki\nMa-te-te-ki-ta-ka-ta\nTiki-tiki-tiki\nMa-te-te-ki-ta-ka-ta\nTiki-tiki-tiki\nMa-te-te-ki-ta-ka-ta\nTiki-tiki-tiki (tiki)\nKi-ta-ka-ta, ta-ka-ta-ta-ta (tiki)\nTiki\nMa-te-te-ki-ta-ka-ta\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nMa-te\nMa-te-te-ki-ta-ka-ta\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki-tiki\nTiki",
    },
    {
        src: "assets-playlists/src/boiadera.mp3",
        name: "Boiadera",
        artist: "Ana Castela",
        cover: "https://i.scdn.co/image/ab67616d0000b27390b146a78697b8b0c4306623",
        lyrics: "Depois que me conheceu já quis se mudar aqui pro interio'\nDeixa o carro na garagem pra andar de mangalarga marchado\nO cabelo Chanel deu lugar pro chapéu\nTá cheia de terra a unha de gel\nO Dolce & Gabanna agora foi trocado\nPor um perfume com cheiro de mato\nEla que era cheia de não me toque\nAgora tá tocando o gado\nA maquiagem dela agora é poeira\nA patricinha virou boiadeira\nLargou o vinho pra tomar cerveja\nA patricinha virou boiadeira\nA maquiagem dela agora é poeira\nA patricinha virou boiadeira\nLargou o vinho pra tomar cerveja\nA patricinha virou boiadeira\nO cabelo Chanel deu lugar pro chapéu\nTá cheia de terra a unha de gel\nO Dolce & Gabanna agora foi trocado\nPor um perfume com cheiro de mato\nEla que era cheia de não me toque\nAgora tá tocando o gado\nA maquiagem dela agora é poeira\nA patricinha virou boiadeira\nLargou o vinho pra tomar cerveja\nA patricinha virou boiadeira\nA maquiagem dela agora é poeira\nA patricinha virou boiadeira\nLargou o vinho pra tomar cerveja\nA patricinha virou boiadeira\nA boiadeira chegou, bebê",
    },
    {
        src: "assets-playlists/src/blame-game.mp3",
        name: "Blame Game",
        artist: "Kanye West, John Legend",
        cover: "https://i.scdn.co/image/ab67616d0000b273d9194aa18fa4c9362b47464f",
        lyrics: "Whose fault?\nLet's play the blame game, I love you more\nLet's play the blame game for sure\nLet's call out names, names, I hate you more\nLet's call out names, names for sure\nI'll call you bitch for short\nAs a last resort and my first resort\nYou call me motherfucker for long\nAt the end of it, you know we both were wrong\nBut I love to play the blame game, I love you more\nLet's play the blame game for sure\nLet's call out names, names, I hate you more\nLet's call out names, names for sure\nOn the bathroom wall I wrote\n'I'd rather argue with you than to be with someone else'\nI took a piss and dismiss it like 'fuck it'\nAnd I went and found somebody else\nFuck arguing and harvesting the feelings\nYo, I'd rather be by my fuckin' self\n'Til about 2 a.m. and I call back\nAnd I hang up and I start to blame myself\nSomebody help\nLet's play the blame game, I love you more\nLet's play the blame game for sure\nLet's call out names, names, I hate you more\nLet's call out names, names for sure\nYou weren't perfect, but you made life worth it\nStick around, some real feelings might surface\nBeen a long time since I spoke to you in a bathroom\nGrippin' you up, fuckin' and chokin' you\nWhat the hell was I supposed to do?\nI know you ain't gettin' this type of dick from that local dude\nAnd if you are, I hope you have a good time\n'Cause I definitely be havin' mine\nAnd you ain't finna see a mogul get emotional\nEvery time I hear about other niggas is strokin' you\nLie and say I hit you, he sittin' there consoling you\nRunnin' my name through the mud, who's provoking you?\nYou should be grateful a nigga like me ever noticed you\nNow you noticeable and can't nobody get control of you\n1 a.m. and can't nobody get a hold of you\nI'm callin' your brother's phone, like, what was I supposed to do?\nEven though I knew he never told the truth\nHe was just gon' say whatever that you told him to\nAt a certain point, I had to stop asking questions\nY'all got dirt on each other like mud wrestlers\nI heard he bought some coke with my money, that ain't right, girl\nYou gettin' blackmailed for that white girl\nYou always said, 'Yeezy, I ain't your right girl\nYou'll probably find one of them 'I like art'-type girls'\n'All of the lights,' she was caught in the hype, girl\nAnd I was satisfied bein' in love with a lie\nNow who to blame? You to blame?\nMe to blame? For the pain\nAnd it poured every time when it rained\nLet's play the blame game, I love you more\nLet's play the blame game for sure\nThings used to be, now they not\nAnything but us is who we are\nDisguising ourselves as secret lover\nWe've become public enemies\nWe walk away like strangers in the street\nGone for eternity\nWe erased one another\nSo far from where we came\nWith so much of everything\nHow do we leave with nothing?\nLack of visual empathy equates the meaning of L-O-V-E\nHatred and attitude tear us entirely\nChloe Mitchell\nLet's play the blame game, I love you more\nLet's play the blame game for sure\nLet's call out names, names, I hate you more\nLet's call out names, names, for sure\nI can't love you this much, I can't love you this much\nI can't love you this much, I can't love you this much\nI can't love you this much, no, I can't love you this much\nI can't love you this much, I can't love you this much\nAnd I know that you are somewhere doing your thing\nAnd when the phone called, it just ring and ring\nYou ain't pick up, but your phone accidentally called me back\nAnd I heard the whole thing\nI heard the whole thing, whole thing, whole thing, whole thing\n['The Best Birthday': Chris Rock & Salma Kenas]\nOh my God\nBaby, you done took this shit to another motherfuckin' level\nNow, a neighborhood nigga like me ain't supposed to be gettin' no pussy like this\nGoddamn, goddamn\nWho taught you how to get sexy for a nigga?\n(Yeezy taught me)\nYou never used to talk dirty, but now you goddamn disgusting\nMy, my God, where'd you learn that?\n(Yeezy taught me)\nLook at you, motherfuckin' butt-ass-naked\nWith them motherfuckin' Jimmy Choos on\nWho taught you how to put some motherfuckin' Jimmy Choos on?\n(Yeezy taught me)\nYo, you took your pussy game up a whole 'nother level\nThis is some Cirque du Soleil pussy now, shit\nYou done went all porno on a nigga, okay?\nAnd I-I-I-I, I love it, and I thank you\nI thank you, my dick thanks you\nHow'd you learn, how, how did your pussy game come up?\n(Yeezy taught me)\nI was fuckin' parts of your pussy I'd never fucked before\nI was in there like, 'Oh shit, I never been here before\nI've never even seen this part of Pussy Town before'\nIt's like you got this shit reupholstered or some shit\nWhat the fuck happened?\nWho, who the fuck got your pussy all reupholstered?\n(Yeezy reupholstered my pussy)\nYou know what, I got to thank Yeezy\nAnd when I see that nigga, I'ma thank him\nI'ma buy the album, I'ma download that motherfucker\nI'ma shoot a bootlegger\nThat's how good I feel about this nigga\nAh\nI still can't believe you got me this watch\nThis motherfucker is the exact motherfucker I wanted\nWith the bezel? This is the motherfucker I wanted\nI saw this shit, I saw it, Twista had this shit on in The Source\nI 'member, Twista had this motherfucker on in The Source\nThat's right, that's right\nYo, yo, babe, yo, yo, this the best birthday ever\nWhere'd you learn to treat a nigga like this?\n(Yeezy taught me)\nYeezy taught you well\nYeezy taught you well",
    },
    {
        src: "assets-playlists/src/spaghetti.mp3",
        name: "SPAGHETTI",
        artist: "LE SSERAFIM, j-hope",
        cover: "https://i.scdn.co/image/ab67616d0000b2736c4a726c271daf4a4b97e35b",
        lyrics: "",
    },
    {
        src: "assets-playlists/src/pela-luz-dos-olhos-teus.mp3",
        name: "Pela Luz dos Olhos Teus",
        artist: "Tom Jobim, Miúcha",
        cover: "https://i.scdn.co/image/ab67616d0000b273ce5e217cf4691d48f5b88a73",
        lyrics: "Quando a luz dos olhos meus\nE a luz dos olhos teus\nResolvem se encontrar\nAi, que bom que isso é meu Deus\nQue frio que me dá o encontro desse olhar\nMas se a luz dos olhos teus\nResiste aos olhos meus\nSó pra me provocar\nMeu amor juro por Deus\nMe sinto incendiar\nMeu amor juro por Deus\nQue a luz dos olhos meus\nJá não pode esperar\nQuero a luz dos olhos meus\nNa luz dos olhos teus\nSem mais la ra ra ra...\nPela luz dos olhos teus\nEu acho meu amor que só se pode achar\nQue a luz dos olhos meus precisa se casar\n(La ra ri ra ra ra...)\n(La ra ri ra ra ra...)\nQuando a luz dos olhos meus\nE a luz dos olhos teus\nResolvem se encontrar\nAi, que bom que isso é meu Deus\nQue frio que me dá o encontro desse olhar\nMas se a luz dos olhos teus\nResiste aos olhos meus\nSó pra me provocar\nMeu amor juro por Deus\nMe sinto incendiar\nMeu amor juro por Deus\nQue a luz dos olhos meus\nJá não pode esperar\nQuero a luz dos olhos meus\nNa luz dos olhos teus\nSem mais la ra ra ra...\nPela luz dos olhos teus\nEu acho meu amor e só se pode achar\nQue a luz dos olhos meus precisa se casar\nQue a luz dos olhos meus precisa se casar\nQue a luz dos olhos meus precisa se casar\nPrecisa se casar, precisa se casar (repete até o fim)"
    },
    {
        src: "assets-playlists/src/construcao.mp3",
        name: "Construção",
        artist: "Chico Buarque",
        cover: "https://i.scdn.co/image/ab67616d0000b273f061d4beecf1d3ebb2c2bb97",
        lyrics: "Amou daquela vez como se fosse a última\nBeijou sua mulher como se fosse a última\nE cada filho seu como se fosse o único\nE atravessou a rua com seu passo tímido\nSubiu a construção como se fosse máquina\nErgueu no patamar quatro paredes sólidas\nTijolo com tijolo num desenho mágico\nSeus olhos embotados de cimento e lágrima \nSentou pra descansar como se fosse sábado\nComeu feijão com arroz como se fosse um príncipe\nBebeu e soluçou como se fosse um náufrago\nDançou e gargalhou como se ouvisse música\nE tropeçou no céu como se fosse um bêbado\nE flutuou no ar como se fosse um pássaro\nE se acabou no chão feito um pacote flácido\nAgonizou no meio do passeio público\nMorreu na contramão atrapalhando o tráfego\nAmou daquela vez como se fosse o último\nBeijou sua mulher como se fosse a única\nE cada filho seu como se fosse o pródigo\nE atravessou a rua com seu passo bêbado\nSubiu na construção como se fosse sólido\nErgueu no patamar quatro paredes mágicas\nTijolo com tijolo num desenho lógico\nSeus olhos embotados de cimento e tráfego\nSentou pra descansar como se fosse um príncipe\nComeu feijão com arroz como se fosse o máximo\nBebeu e soluçou como se fosse máquina\nDançou e gargalhou como se fosse o próximo\nE tropeçou no céu como se ouvisse música\nE flutuou no ar como se fosse sábado\nE se acabou no chão feito um pacote tímido\nAgonizou no meio do passeio náufrago\nMorreu na contramão atrapalhando o público\nAmou daquela vez como se fosse máquina\nBeijou sua mulher como se fosse lógico\nErgueu no patamar quatro paredes flácidas\nSentou pra descansar como se fosse um pássaro\nE flutuou no ar como se fosse um príncipe\nE se acabou no chão feito um pacote bêbado\nMorreu na contramão atrapalhando o sábado\nPor esse pão pra comer, por esse chão pra dormir\nA certidão pra nascer, a concessão pra sorrir\nPor me deixar respirar, por me deixar existir\nDeus lhe pague\nPela cachaça de graça que a gente tem que engolir\nPela fumaça, desgraça, que a gente tem que tossir\nPelos andaimes, pingentes, que a gente tem que cair\nDeus lhe pague\nPela mulher carpideira pra nos louvar e cuspir\nE pelas moscas-bicheiras a nos beijar e cobrir\nE pela paz derradeira que enfim vai nos redimir\nDeus lhe pague",
    },
];