export default [
    {
        src: "assets-playlists/src/something-stupid.mp3",
        name: "Something Stupid",
        artist: "Frank Sinatra & Nancy Sinatra",
        cover: "https://i.scdn.co/image/ab67616d0000b2733e2331ff09f59ea3c87fe5d6",
        lyrics: "I know I stand in line\nUntil you think you have the time\nTo spend an evening with me\nAnd if we go some place to dance\nI know that there's a chance\nYou won't be leaving with me\nThen afterwards we drop into a quiet little place\nAnd have a drink or two\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\nI can see it in your eyes\nThat you despise the same old lies\nYou heard the night before\nAnd though it's just a line to you\nFor me it's true\nAnd never seemed so right before\nI practice every day \nTo find some clever lines to say\nTo make the meaning come true\nBut then I think I'll wait\nUntil the evening gets late\nAnd I'm alone with you\nThe time is right, your perfume fills my head\nThe stars get red, and, oh, the night's so blue\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\nThe time is right, your perfume fills my head\nThe stars get red, and, oh, the night's so blue\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\n'I love you'\n'I love you\n'I love you'\n'I love you'",
    },
    {
        src: "assets-playlists/src/zombie.mp3",
        name: "Zombie",
        artist: "The Cranberries",
        cover: "https://i.scdn.co/image/ab67616d0000b273e2213d84fabb15100c425198",
        lyrics: "Another head hangs lowly\nChild is slowly taken\nAnd the violence caused such silence\nWho are we mistaken?\nBut you see, it's not me, it's not my family\nIn your head, in your head, they are fightin'\nWith their tanks and their bombs\nAnd their bombs and their guns\nIn your head, in your head, they are cryin'\nIn your head, in your head\nZombie, zombie, zombie-ie-ie\nWhat's in your head, in your head?\nZombie, zombie, zombie-ie-ie-ie, oh\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nAnother mother's breakin'\nHeart is taking over\nWhen the violence causes silence\nWe must be mistaken\nIt's the same old theme, since 1916\nIn your head, in your head, they're still fightin'\nWith their tanks and their bombs\nAnd their bombs and their gun\nIn your head, in your head, they are dyin'\nIn your head, in your head\nZombie, zombie, zombie-ie-ie\nWhat's in your head, in your head?\nZombie, zombie, zombie-ie-ie-ie\nOh-oh-oh-oh-oh-oh-oh\nEh-eh, oh, ya-ya\n",
    },
    {
        src: "assets-playlists/src/clint-eastwood.mp3",
        name: "Clint Eastwood",
        artist: "Gorillaz",
        cover: "https://i.scdn.co/image/ab67616d0000b273c73a7bb15f43bae86215934b",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/apocalypse.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/505.mp3",
        name: "505",
        artist: "Arctic Monkeys",
        cover: "https://i.scdn.co/image/ab67616d0000b2730c8ac83035e9588e8ad34b90",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/there-is-a-light-that-never-goes-out.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/let-it-happen.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/thats-life.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/é-preciso-saber-viver.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/otherside.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/my-way.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/freaking-out-the-neighborhood.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/dont-look-back-in-anger.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/the-less-i-know-the-better.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/baby-blue.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/heart-attack.mp3",
        name: "Heart Attack (츄)",
        artist: "LOONA",
        cover: "https://i.scdn.co/image/ab67616d0000b273b6ab7be3b4eeb27e1af65cdb",
        lyrics: "Are you ready? (Ah)\nYou attack my heart\nYou attack my heart (Ah)\nYou attack my heart\nYou attack my heart (Damn)\n우리 처음 봤던 날 조용했던 내 맘 속\n새로운 세상이 열린 듯\n유난히 빨라지던 move\n나 혼자 알고 있었던 감춰진 내 비밀도\n너에게 딱 내 전부다\n말하고 싶어지던 mood\n나 한 걸음 먼저 널 향해 먼저\n다가간 모습에\n숨어있던 날 만나게 돼 (Oh)\n점점 더 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득히\n아찔한 기분이\n이런 건가 봐, darling\n점점 더 난 네게 빠져가\nYou attack my heart\nYou attack my heart\nYou attack my heart (Ah)\nYou attack my heart\nYou attack my heart (Damn)\n이런 게 fall in love 하얀 내 맘에\n너를 담았더니 빨간색이 돼\n멈출 수 없이 자꾸 떠올라\n유난히 더 많이 생각하게 돼\n내 모든 기준들이 너로 정해져 버리듯\n지구를 맴맴 도는 저기 달처럼\n우린 ooh-ooh, 만나게 될 거야\nOn the ooh-ooh-ooh, on the love trail\n널 보면 반짝 내 맘에 반짝\n불꽃이 튀는 듯\n숨어있던 맘을 알게 돼 (Oh)\n점점 더 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득히\n아찔한 기분이\n이런 건가 봐, darling\n점점 더 난 네게 빠져가\nYou attack my heart\n시간의 흐름도 모를 만큼\nAnywhere, anywhere, 널 생각해\nAnytime, anyplace, 너로 가득\n끝없이 퍼져\n조금 더 가까이 다가와줘\n우리 둘 함께 마주한다면\n상상조차 달콤하게만\n느껴져\n널 향해 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득해\n점점 더 선명해진 맘\n전부 다 줄게 take my heart\n분명 우리는 destiny (Destiny)\n빛이나 이 밤 가득히\n달콤한 중독이\n이런 건가 봐, darling\n더 깊이 너에게 빠져가 (Ooh-ooh, ooh-ooh)\n점점 더 두근대는 맘\n전부 다 줄게 take my heart\n분명 넌 나의 destiny\n빛이나 내 맘 가득히 (Take my, take my heart)\n아찔한 기분이\n이런 건가 봐, darling\n점점 더 난 네게 빠져가\nYou attack my heart",
    },
    {
        src: "assets-playlists/src/pelados-em-santos.mp3",
        name: "Pelados Em Santos",
        artist: "Mamonas Assassinas",
        cover: "https://i.scdn.co/image/ab67616d0000b2733982e253126c959ab9677bcb",
        lyrics: "Mina, seus cabelo é da hora, seu corpo violão\nMeu docinho de coco, tá me deixando louco\nMinha Brasília amarela tá de portas abertas\nPra mode a gente se amar pelados em Santos\nPois você, minha pitchula, me deixou legalzão\nNão me sinto sozinho, você é meu chuchuzinho\nMusic is very good\n(Oxente ai, ai, ai)\nMas comigo, ela não quer se casar\n(Oxente ai, ai, ai)\nNa Brasília amarela com roda Gaúcha, ela não quer entrar\n(Oxente ai, ai, ai)\nÉ, feijão com jabá, desgraçada, não quer compartilhar\nMas ela é linda\nMuito mais do que linda\nVery, very beautiful\nVocê me deixa doidão\nOh, yes, oh, no's\nMeu docinho de coco\nMusic is very porreta\n(Oxente, Paraguai)\nPros Paraguai, ela não quis viajar\n(Oxente, Paraguai)\nComprei um Reebok e uma calça Fiorucci, ela não quer usar\n(Oxente, Paraguai)\nEu não sei o que faço, pra essa mulher eu conquistar\nPorque ela é linda\nMuito mais do que linda\nVery, very beautiful\nVocê me deixa doidão\nOh, yes, oh, no's\nMeu chuchuzinho\nOh, yes, no, no, no, no\nEu te I love you\nPeraí, que tem mais um pouquinho de 'u'\nUuuuu\nTchê",
    },
    {
        src: "assets-playlists/src/triple-baka.mp3",
        name: "Triple Baka",
        artist: "Hatsune Miku, Akita Neru, Kasane Teto",
        cover: "https://i.scdn.co/image/ab67616d0000b2734cbf7f307793e3ccac71ce9b",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/smile.mp3",
        name: "Smile",
        artist: "Lily Allen",
        cover: "https://i.scdn.co/image/ab67616d0000b273903b3846b9843677ca51bad9",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/diga-sim-pra-mim.mp3",
        name: "Diga Sim pra Mim",
        artist: "Desejo De Menina",
        cover: "https://i.scdn.co/image/ab67616d0000b2730608a3c6880ab70a40eb7827",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/cradles.mp3",
        name: "Cradles",
        artist: "Sub Urban",
        cover: "https://i.scdn.co/image/ab67616d0000b273e57adcac43f4e49de7cdc65e",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/chic-n-stu.mp3",
        name: "Chic 'N' Stu",
        artist: "System Of A Down",
        cover: "https://i.scdn.co/image/ab67616d0000b2737cf4c0d42c5b62c9deebdcd8",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/yummy.mp3",
        name: "Yummy",
        artist: "Ayesha Erotica",
        cover: "https://i.scdn.co/image/ab67616d0000b27370cdf4fc0b6b2dc937e2290e",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/tiki-tiki.mp3",
        name: "TIKI TIKI (Slowed)",
        artist: "QMIIR, SLIMA CHICA",
        cover: "https://i.scdn.co/image/ab67616d0000b27301913aba303b2a409c0cd157",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/boiadera.mp3",
        name: "Boiadera",
        artist: "Ana Castela",
        cover: "https://i.scdn.co/image/ab67616d0000b27390b146a78697b8b0c4306623",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/blame-game.mp3",
        name: "Blame Game",
        artist: "Kanye West, John Legend",
        cover: "https://i.scdn.co/image/ab67616d0000b273d9194aa18fa4c9362b47464f",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/spaghetti.mp3",
        name: "SPAGHETTI",
        artist: "LE SSERAFIM, j-hope",
        cover: "https://i.scdn.co/image/ab67616d0000b2736c4a726c271daf4a4b97e35b",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/pela-luz-dos-olhos-teus.mp3",
        name: "Pela Luz dos Olhos Teus",
        artist: "Tom Jobim, Miúcha",
        cover: "https://i.scdn.co/image/ab67616d0000b273ce5e217cf4691d48f5b88a73",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/contrucao.mp3",
        name: "Construção",
        artist: "Chico Buarque",
        cover: "https://i.scdn.co/image/ab67616d0000b273f061d4beecf1d3ebb2c2bb97",
        lyrics: "vamo\nclint\n",
    },
];