export default [
    {
        src: "assets-playlists/src/something-stupid.mp3",
        name: "Something Stupid",
        artist: "Frank Sinatra & Nancy Sinatra",
        cover: "https://i.scdn.co/image/ab67616d0000b2733e2331ff09f59ea3c87fe5d6",
        lyrics: "I know I stand in line\nUntil you think you have the time\nTo spend an evening with me\nAnd if we go some place to dance\nI know that there's a chance\nYou won't be leaving with me\nThen afterwards we drop into a quiet little place\nAnd have a drink or two\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\nI can see it in your eyes\nThat you despise the same old lies\nYou heard the night before\nAnd though it's just a line to you\nFor me it's true\nAnd never seemed so right before\nI practice every day \nTo find some clever lines to say\nTo make the meaning come true\nBut then I think I'll wait\nUntil the evening gets late\nAnd I'm alone with you\nThe time is right, your perfume fills my head\nThe stars get red, and, oh, the night's so blue\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\nThe time is right, your perfume fills my head\nThe stars get red, and, oh, the night's so blue\nAnd then I go and spoil it all\nBy saying somethin' stupid like, 'I love you'\n'I love you'\n'I love you\n'I love you'\n'I love you'",
    },
    {
        src: "assets-playlists/src/zombie.mp3",
        name: "Zombie",
        artist: "The Cranberries",
        cover: "https://i.scdn.co/image/ab67616d0000b273e2213d84fabb15100c425198",
        lyrics: "Another head hangs lowly\nChild is slowly taken\nAnd the violence caused such silenceWho are we mistaken?But you see, it's not me, it's not my familyIn your head, in your head, they are fightin'\nWith their tanks and their bombs\nAnd their bombs and their guns\nIn your head, in your head, they are cryin'\nIn your head, in your head\nZombie, zombie, zombie-ie-ie\nWhat's in your head, in your head?\nZombie, zombie, zombie-ie-ie-ie, oh\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nDoo, doo, doo-doo, doo\nAnother mother's breakin'\nHeart is taking over\nWhen the violence causes silence\nWe must be mistaken\nIt's the same old theme, since 1916\nIn your head, in your head, they're still fightin'\nWith their tanks and their bombs\nAnd their bombs and their gun\nIn your head, in your head, they are dyin'\nIn your head, in your head\nZombie, zombie, zombie-ie-ie\nWhat's in your head, in your head?\nZombie, zombie, zombie-ie-ie-ie\nOh-oh-oh-oh-oh-oh-oh\nEh-eh, oh, ya-ya",
    },
    {
        src: "assets-playlists/src/clint-eastwood.mp3",
        name: "Clint Eastwood",
        artist: "Gorillaz",
        cover: "https://i.scdn.co/image/ab67616d0000b273c73a7bb15f43bae86215934b",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/apocalypse.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/505.mp3",
        name: "505",
        artist: "Arctic Monkeys",
        cover: "https://i.scdn.co/image/ab67616d0000b2730c8ac83035e9588e8ad34b90",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/there-is-a-light-that-never-goes-out.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/let-it-happen.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/thats-life.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/é-preciso-saber-viver.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/otherside.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/my-way.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/freaking-out-the-neighborhood.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/dont-look-back-in-anger.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/the-less-i-know-the-better.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
    {
        src: "assets-playlists/src/baby-blue.mp3",
        name: "",
        artist: "",
        cover: "",
        lyrics: "vamo\nclint\n",
    },
];